In [702]:
#lin alg
import numpy as np

#csv IOs and dataframes
import pandas as pd

#clustering
from sklearn.cluster import KMeans

import matplotlib.pyplot as plt

%matplotlib notebook

### Hello DST!
#### This notebook is the first installation of a series of data science tutorials. 

##### I am planning on walking you through how to do some simple data engineering, where we will focus on intake and subsequently cleaning/processing. After that, I will show you how to do a simple model inference. For our dataset we will be using the kmeans model supplied by sklean

## Data Engineering

In [703]:
#This can be a relative or absolute path. In actual work it will very highly on your envoirment
df = pd.read_csv('family_matching.csv') 

#more on these two later
drop_cols = set([]) 
id_cols = set([])

In [704]:
#Lets take a look at our survey results, what are its dimensions?
df.shape

(29, 46)

#### Normally, our data would be too large to see at a glance in a notebook

#### so we would have to use the head() funct given by dataframes, but here we have

#### such a small dataset its fine either way.

In [705]:
df

,Timestamp,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,...,Do you like Indie music?,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.
0,2021/02/02 7:49:10 PM EST,linsyw@bu.edu,Linsy,Wang,Yes,Yes,Yes,Yes,Yes,Yes,...,Yes,No,No,Yes,No,No,Yes,Yes,No,No
1,2021/02/02 7:49:12 PM EST,pkuzdzal@bu.edu,Patrick,Kuzdzal,No,Yes,Yes,Yes,No,No,...,Yes,No,Yes,No,No,No,Yes,No,No,No
2,2021/02/02 7:49:14 PM EST,emcateer@bu.edu,Erin,McAteer,Yes,Yes,Yes,Yes,Yes,No,...,Yes,No,Yes,No,No,No,Yes,No,No,No
3,2021/02/02 7:49:19 PM EST,vitor@bu.edu,Victor,Vicente,Yes,Yes,No,Yes,Yes,Yes,...,Yes,No,No,No,No,Yes,Yes,No,Yes,No
4,2021/02/02 7:49:22 PM EST,srk22@bu.edu,Snigdha,Kalathur,Yes,No,Yes,Yes,Yes,No,...,No,No,No,No,No,No,Yes,No,No,Yes
5,2021/02/02 7:49:30 PM EST,johnbest@bu.edu,John,Bestavros,Yes,Yes,No,Yes,No,Yes,...,No,No,Yes,No,No,No,Yes,No,Yes,Yes
6,2021/02/02 7:49:45 PM EST,cewalsh@bu.edu,Conor,Walsh,Yes,No,No,Yes,Yes,Yes,...,Yes,No,Yes,No,No,No,Yes,No,No,No
7,2021/02/02 7:50:06 PM EST,sid15@bu.edu,Siddhant,Kothari,Yes,Yes,No,Yes,Yes,No,...,No,No,No,No,No,Yes,Yes,Yes,No,No
8,2021/02/02 7:50:08 PM EST,zwan1312@bu.edu,Zhenghui,Wang,Yes,No,No,Yes,Yes,No,...,Yes,No,Yes,No,No,No,Yes,No,Yes,No
9,2021/02/02 7:50:11 PM EST,shkim219@bu.edu,Seonghoo (Paul),Kim,Yes,No,Yes,Yes,Yes,No,...,Yes,Yes,Yes,No,No,No,No,Yes,No,Yes
10,2021/02/02 7:50:27 PM EST,gmoncau@bu.edu,Gabriel,Moncau,Yes,Yes,Yes,No,No,No,...,Yes,Yes,Yes,No,No,No,Yes,No,No,No
11,2021/02/02 7:50:56 PM EST,kszhao@bu.edu,Kradon,Zhao,Yes,No,No,Yes,Yes,Yes,...,No,No,Yes,No,No,No,Yes,Yes,No,Yes
12,2021/02/02 7:51:05 PM EST,jcbolo@bu.edu,John,Bolognino,Yes,Yes,No,Yes,Yes,Yes,...,Yes,No,Yes,No,No,Yes,Yes,No,No,Yes
13,2021/02/02 7:51:28 PM EST,upe@bu.edu,Amy,Feng,No,Yes,Yes,Yes,Yes,No,...,No,No,Yes,No,No,No,Yes,No,No,Yes
14,2021/02/02 7:51:32 PM EST,carlopez@bu.edu,Carlos,Lopez,Yes,Yes,Yes,Yes,Yes,Yes,...,Yes,No,No,Yes,No,No,Yes,No,Yes,Yes
15,2021/02/02 7:51:32 PM EST,darogers@bu.edu,Delaine,Rogers,Yes,Yes,Yes,Yes,Yes,No,...,Yes,Yes,Yes,No,No,No,Yes,No,No,Yes
16,2021/02/02 7:51:32 PM EST,ebudur@bu.edu,Eren,Budur,Yes,Yes,No,Yes,No,Yes,...,Yes,No,Yes,No,No,No,Yes,No,No,No
17,2021/02/02 7:52:19 PM EST,janamha@bu.edu,Jana Mikaela,Aguilar,Yes,No,Yes,Yes,Yes,No,...,Yes,Yes,No,No,No,Yes,Yes,No,No,No
18,2021/02/02 7:52:24 PM EST,dsullo@bu.edu,David,Sullo,Yes,No,Yes,Yes,Yes,Yes,...,Yes,No,Yes,No,No,No,Yes,No,Yes,No
19,2021/02/02 7:52:26 PM EST,dcmag@bu.edu,Dominic,Maglione,No,Yes,No,Yes,Yes,No,...,No,No,Yes,No,No,No,Yes,No,No,No
20,2021/02/02 7:52:38 PM EST,benjisg@bu.edu,Benji,Spetter-Goldstein,Yes,Yes,Yes,Yes,Yes,No,...,Yes,No,No,No,No,No,Yes,No,No,No
21,2021/02/02 7:52:43 PM EST,scarden@bu.edu,Savannah,Cardenas,Yes,Yes,Yes,Yes,Yes,No,...,Yes,Yes,Yes,No,No,No,Yes,No,No,No
22,2021/02/02 7:52:51 PM EST,agu2002@bu.edu,Anming,Gu,Yes,Yes,Yes,Yes,Yes,Yes,...,No,Yes,No,No,No,No,Yes,Yes,No,Yes
23,2021/02/02 7:53:17 PM EST,fgpacini@bu.edu,Francis,Pacini,Yes,Yes,No,Yes,Yes,No,...,Yes,No,No,No,Yes,No,Yes,No,No,Yes
24,2021/02/02 7:53:48 PM EST,pkumari@bu.edu,Priya,Kumari,No,Yes,No,Yes,Yes,No,...,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes
25,2021/02/02 7:54:21 PM EST,mlopez99@bu.edu,Melissa,Lopez,Yes,No,No,Yes,Yes,No,...,No,Yes,Yes,No,No,No,Yes,No,Yes,Yes
26,2021/02/02 7:54:27 PM EST,mhenrik@bu.edu,Matt,Henriksen,Yes,Yes,Yes,Yes,Yes,No,...,No,No,Yes,No,No,No,Yes,No,No,No
27,2021/02/02 7:55:03 PM EST,evanlhsu@bu.edu,Evan,Hsu,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,No,Yes,No,Yes,No,No,No
28,2021/02/02 7:59:22 PM EST,nathanhh@bu.edu,Nathan,Ho,Yes,No,No,Yes,No,Yes,...,No,No,No,No,No,No,Yes,No,No,Yes

In [706]:
df.head()

,Timestamp,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,...,Do you like Indie music?,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.
0,2021/02/02 7:49:10 PM EST,linsyw@bu.edu,Linsy,Wang,Yes,Yes,Yes,Yes,Yes,Yes,...,Yes,No,No,Yes,No,No,Yes,Yes,No,No
1,2021/02/02 7:49:12 PM EST,pkuzdzal@bu.edu,Patrick,Kuzdzal,No,Yes,Yes,Yes,No,No,...,Yes,No,Yes,No,No,No,Yes,No,No,No
2,2021/02/02 7:49:14 PM EST,emcateer@bu.edu,Erin,McAteer,Yes,Yes,Yes,Yes,Yes,No,...,Yes,No,Yes,No,No,No,Yes,No,No,No
3,2021/02/02 7:49:19 PM EST,vitor@bu.edu,Victor,Vicente,Yes,Yes,No,Yes,Yes,Yes,...,Yes,No,No,No,No,Yes,Yes,No,Yes,No
4,2021/02/02 7:49:22 PM EST,srk22@bu.edu,Snigdha,Kalathur,Yes,No,Yes,Yes,Yes,No,...,No,No,No,No,No,No,Yes,No,No,Yes

The general goal of data engineering is to create a pipeline that can intake data, and make it digestible for a computer model.

What is digestible?

The root of computer models tend to generally be linear algebra. Therefore anything input that is not a number, is not useable in its raw form. 

To remedy this, we transform the data in something there computer can understand, and then we can run it through models. In this exercise we are going to run through some different types of data, and how it is useful to us. So lets go through our data column by column

In [707]:
#first column
col_1 = df['Timestamp']
pd.DataFrame(col_1) #this casting is just to make it look nice

                    Timestamp
0   2021/02/02 7:49:10 PM EST
1   2021/02/02 7:49:12 PM EST
2   2021/02/02 7:49:14 PM EST
3   2021/02/02 7:49:19 PM EST
4   2021/02/02 7:49:22 PM EST
5   2021/02/02 7:49:30 PM EST
6   2021/02/02 7:49:45 PM EST
7   2021/02/02 7:50:06 PM EST
8   2021/02/02 7:50:08 PM EST
9   2021/02/02 7:50:11 PM EST
10  2021/02/02 7:50:27 PM EST
11  2021/02/02 7:50:56 PM EST
12  2021/02/02 7:51:05 PM EST
13  2021/02/02 7:51:28 PM EST
14  2021/02/02 7:51:32 PM EST
15  2021/02/02 7:51:32 PM EST
16  2021/02/02 7:51:32 PM EST
17  2021/02/02 7:52:19 PM EST
18  2021/02/02 7:52:24 PM EST
19  2021/02/02 7:52:26 PM EST
20  2021/02/02 7:52:38 PM EST
21  2021/02/02 7:52:43 PM EST
22  2021/02/02 7:52:51 PM EST
23  2021/02/02 7:53:17 PM EST
24  2021/02/02 7:53:48 PM EST
25  2021/02/02 7:54:21 PM EST
26  2021/02/02 7:54:27 PM EST
27  2021/02/02 7:55:03 PM EST
28  2021/02/02 7:59:22 PM EST

In [708]:
# notice that it is a type "Timestamp"?
col_1

0     2021/02/02 7:49:10 PM EST
1     2021/02/02 7:49:12 PM EST
2     2021/02/02 7:49:14 PM EST
3     2021/02/02 7:49:19 PM EST
4     2021/02/02 7:49:22 PM EST
5     2021/02/02 7:49:30 PM EST
6     2021/02/02 7:49:45 PM EST
7     2021/02/02 7:50:06 PM EST
8     2021/02/02 7:50:08 PM EST
9     2021/02/02 7:50:11 PM EST
10    2021/02/02 7:50:27 PM EST
11    2021/02/02 7:50:56 PM EST
12    2021/02/02 7:51:05 PM EST
13    2021/02/02 7:51:28 PM EST
14    2021/02/02 7:51:32 PM EST
15    2021/02/02 7:51:32 PM EST
16    2021/02/02 7:51:32 PM EST
17    2021/02/02 7:52:19 PM EST
18    2021/02/02 7:52:24 PM EST
19    2021/02/02 7:52:26 PM EST
20    2021/02/02 7:52:38 PM EST
21    2021/02/02 7:52:43 PM EST
22    2021/02/02 7:52:51 PM EST
23    2021/02/02 7:53:17 PM EST
24    2021/02/02 7:53:48 PM EST
25    2021/02/02 7:54:21 PM EST
26    2021/02/02 7:54:27 PM EST
27    2021/02/02 7:55:03 PM EST
28    2021/02/02 7:59:22 PM EST
Name: Timestamp, dtype: object

There are multiple ways to clean a timestamp; however, for our purposes we do not need them. The time someone completes this test will probably not be indictive of our data. For now, we will just drop this column.

If you guys want to learn more about how to deal with time data, let me known in the gc. Timestamps are mostly used in time-series based models, which is a completely different beast. So instead, lets mark this column for deletion.

In [709]:
#drop_cols is a set that was defined earlier. Do you know why I used a set?

drop_cols.add('Timestamp')

#### Now lets look at the next three columns.

In [710]:
df[['Username', 'First Name', 'Last Name']]

           Username       First Name          Last Name
0     linsyw@bu.edu            Linsy               Wang
1   pkuzdzal@bu.edu          Patrick            Kuzdzal
2   emcateer@bu.edu             Erin            McAteer
3      vitor@bu.edu           Victor            Vicente
4      srk22@bu.edu          Snigdha           Kalathur
5   johnbest@bu.edu             John          Bestavros
6    cewalsh@bu.edu            Conor              Walsh
7      sid15@bu.edu        Siddhant             Kothari
8   zwan1312@bu.edu        Zhenghui                Wang
9   shkim219@bu.edu  Seonghoo (Paul)                Kim
10   gmoncau@bu.edu          Gabriel             Moncau
11    kszhao@bu.edu           Kradon               Zhao
12    jcbolo@bu.edu             John          Bolognino
13       upe@bu.edu              Amy               Feng
14  carlopez@bu.edu           Carlos              Lopez
15  darogers@bu.edu          Delaine             Rogers
16    ebudur@bu.edu             Eren              Budur
17   janamha@bu.edu     Jana Mikaela            Aguilar
18    dsullo@bu.edu            David              Sullo
19     dcmag@bu.edu          Dominic           Maglione
20   benjisg@bu.edu            Benji  Spetter-Goldstein
21   scarden@bu.edu         Savannah           Cardenas
22   agu2002@bu.edu           Anming                 Gu
23  fgpacini@bu.edu          Francis             Pacini
24   pkumari@bu.edu            Priya             Kumari
25  mlopez99@bu.edu          Melissa              Lopez
26   mhenrik@bu.edu             Matt          Henriksen
27  evanlhsu@bu.edu             Evan                Hsu
28  nathanhh@bu.edu           Nathan                 Ho

These columns are not really useful to our model. Unless we are planning to run some Natural Language Processing, which is much more complicated, we cannot really feed these into our model.

However instead of dropping it like we did with Timestamp, we should keep these columns vectors. The time-stamp is relatively useless, but these columns are needed. If we get rid of them, the rest of the data is useless because we wont know who is in clustered.

In [711]:
id_cols = set(['Username', 'First Name', 'Last Name'])

Now lets take a look at the `Grade` column vector.

It is a very interesting case. We don't want the model to treat the different grades on the same linear scale. Instead we are going to treat it as categorical variables (I talked about this in our meeting) if you want to learn more about categorical variables read this: [link for theory](https://stats.idre.ucla.edu/other/mult-pkg/whatstat/what-is-the-difference-between-categorical-ordinal-and-numerical-variables/), [link for application](https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html).

We are going to use One-Hot Encoding.

Unlike a traditional categorical variable, our Grade vector is _technically_ an ordinal variable. This is because unlike a traditional categorical, there is an intuitive relationship (Freshman -> Sophmore -> Junior -> Senior). However by setting them up as different dimensions, our model will be able to cluster more efficiently.

In [712]:
# Lets see if we have every grade here:
df['Do you like vanilla ice cream?'].unique()

array(['Yes', 'No'], dtype=object)

#### Since we do not have seniors here, we only have 3 categorical variables. 

#### Therefore we only need 2 new dimensions. If we were running a neural net we would want all 3, but for our purposes we want to stick with just 2 new dimensions. If you are interested in learning why, look up multicollinearity and "dummy variable trap"

In [713]:
grade_df = pd.get_dummies(df['Do you like vanilla ice cream?'], drop_first=True)
grade_df

    Yes
0     1
1     0
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    0
14    1
15    1
16    1
17    1
18    1
19    0
20    1
21    1
22    1
23    1
24    0
25    1
26    1
27    1
28    1

In [714]:
# Now lets add this back to our data, and get rid of the old column
df[grade_df.columns] = grade_df

In [715]:
df

,Timestamp,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,...,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.,Yes
0,2021/02/02 7:49:10 PM EST,linsyw@bu.edu,Linsy,Wang,Yes,Yes,Yes,Yes,Yes,Yes,...,No,No,Yes,No,No,Yes,Yes,No,No,1
1,2021/02/02 7:49:12 PM EST,pkuzdzal@bu.edu,Patrick,Kuzdzal,No,Yes,Yes,Yes,No,No,...,No,Yes,No,No,No,Yes,No,No,No,0
2,2021/02/02 7:49:14 PM EST,emcateer@bu.edu,Erin,McAteer,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,No,No,Yes,No,No,No,1
3,2021/02/02 7:49:19 PM EST,vitor@bu.edu,Victor,Vicente,Yes,Yes,No,Yes,Yes,Yes,...,No,No,No,No,Yes,Yes,No,Yes,No,1
4,2021/02/02 7:49:22 PM EST,srk22@bu.edu,Snigdha,Kalathur,Yes,No,Yes,Yes,Yes,No,...,No,No,No,No,No,Yes,No,No,Yes,1
5,2021/02/02 7:49:30 PM EST,johnbest@bu.edu,John,Bestavros,Yes,Yes,No,Yes,No,Yes,...,No,Yes,No,No,No,Yes,No,Yes,Yes,1
6,2021/02/02 7:49:45 PM EST,cewalsh@bu.edu,Conor,Walsh,Yes,No,No,Yes,Yes,Yes,...,No,Yes,No,No,No,Yes,No,No,No,1
7,2021/02/02 7:50:06 PM EST,sid15@bu.edu,Siddhant,Kothari,Yes,Yes,No,Yes,Yes,No,...,No,No,No,No,Yes,Yes,Yes,No,No,1
8,2021/02/02 7:50:08 PM EST,zwan1312@bu.edu,Zhenghui,Wang,Yes,No,No,Yes,Yes,No,...,No,Yes,No,No,No,Yes,No,Yes,No,1
9,2021/02/02 7:50:11 PM EST,shkim219@bu.edu,Seonghoo (Paul),Kim,Yes,No,Yes,Yes,Yes,No,...,Yes,Yes,No,No,No,No,Yes,No,Yes,1
10,2021/02/02 7:50:27 PM EST,gmoncau@bu.edu,Gabriel,Moncau,Yes,Yes,Yes,No,No,No,...,Yes,Yes,No,No,No,Yes,No,No,No,1
11,2021/02/02 7:50:56 PM EST,kszhao@bu.edu,Kradon,Zhao,Yes,No,No,Yes,Yes,Yes,...,No,Yes,No,No,No,Yes,Yes,No,Yes,1
12,2021/02/02 7:51:05 PM EST,jcbolo@bu.edu,John,Bolognino,Yes,Yes,No,Yes,Yes,Yes,...,No,Yes,No,No,Yes,Yes,No,No,Yes,1
13,2021/02/02 7:51:28 PM EST,upe@bu.edu,Amy,Feng,No,Yes,Yes,Yes,Yes,No,...,No,Yes,No,No,No,Yes,No,No,Yes,0
14,2021/02/02 7:51:32 PM EST,carlopez@bu.edu,Carlos,Lopez,Yes,Yes,Yes,Yes,Yes,Yes,...,No,No,Yes,No,No,Yes,No,Yes,Yes,1
15,2021/02/02 7:51:32 PM EST,darogers@bu.edu,Delaine,Rogers,Yes,Yes,Yes,Yes,Yes,No,...,Yes,Yes,No,No,No,Yes,No,No,Yes,1
16,2021/02/02 7:51:32 PM EST,ebudur@bu.edu,Eren,Budur,Yes,Yes,No,Yes,No,Yes,...,No,Yes,No,No,No,Yes,No,No,No,1
17,2021/02/02 7:52:19 PM EST,janamha@bu.edu,Jana Mikaela,Aguilar,Yes,No,Yes,Yes,Yes,No,...,Yes,No,No,No,Yes,Yes,No,No,No,1
18,2021/02/02 7:52:24 PM EST,dsullo@bu.edu,David,Sullo,Yes,No,Yes,Yes,Yes,Yes,...,No,Yes,No,No,No,Yes,No,Yes,No,1
19,2021/02/02 7:52:26 PM EST,dcmag@bu.edu,Dominic,Maglione,No,Yes,No,Yes,Yes,No,...,No,Yes,No,No,No,Yes,No,No,No,0
20,2021/02/02 7:52:38 PM EST,benjisg@bu.edu,Benji,Spetter-Goldstein,Yes,Yes,Yes,Yes,Yes,No,...,No,No,No,No,No,Yes,No,No,No,1
21,2021/02/02 7:52:43 PM EST,scarden@bu.edu,Savannah,Cardenas,Yes,Yes,Yes,Yes,Yes,No,...,Yes,Yes,No,No,No,Yes,No,No,No,1
22,2021/02/02 7:52:51 PM EST,agu2002@bu.edu,Anming,Gu,Yes,Yes,Yes,Yes,Yes,Yes,...,Yes,No,No,No,No,Yes,Yes,No,Yes,1
23,2021/02/02 7:53:17 PM EST,fgpacini@bu.edu,Francis,Pacini,Yes,Yes,No,Yes,Yes,No,...,No,No,No,Yes,No,Yes,No,No,Yes,1
24,2021/02/02 7:53:48 PM EST,pkumari@bu.edu,Priya,Kumari,No,Yes,No,Yes,Yes,No,...,No,Yes,No,No,No,Yes,Yes,No,Yes,0
25,2021/02/02 7:54:21 PM EST,mlopez99@bu.edu,Melissa,Lopez,Yes,No,No,Yes,Yes,No,...,Yes,Yes,No,No,No,Yes,No,Yes,Yes,1
26,2021/02/02 7:54:27 PM EST,mhenrik@bu.edu,Matt,Henriksen,Yes,Yes,Yes,Yes,Yes,No,...,No,Yes,No,No,No,Yes,No,No,No,1
27,2021/02/02 7:55:03 PM EST,evanlhsu@bu.edu,Evan,Hsu,Yes,Yes,Yes,Yes,Yes,No,...,Yes,No,No,Yes,No,Yes,No,No,No,1
28,2021/02/02 7:59:22 PM EST,nathanhh@bu.edu,Nathan,Ho,Yes,No,No,Yes,No,Yes,...,No,No,No,No,No,Yes,No,No,Yes,1

#### We are almost there now. The last few columns are all numeric. Lets just practice filtering them. I'll show you a few different ways

In [716]:
df['Are you interested in Product Management?'].unique()

array(['Yes', 'No'], dtype=object)

In [717]:
# Lets make it a simple 0 or 1
for question in df:
    if(not question in id_cols and not question in drop_cols):
        df[question] = df[question].apply(lambda x: 0 if x=='No' else 1)

In [718]:
df

,Timestamp,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,...,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.,Yes
0,2021/02/02 7:49:10 PM EST,linsyw@bu.edu,Linsy,Wang,1,1,1,1,1,1,...,0,0,1,0,0,1,1,0,0,1
1,2021/02/02 7:49:12 PM EST,pkuzdzal@bu.edu,Patrick,Kuzdzal,0,1,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
2,2021/02/02 7:49:14 PM EST,emcateer@bu.edu,Erin,McAteer,1,1,1,1,1,0,...,0,1,0,0,0,1,0,0,0,1
3,2021/02/02 7:49:19 PM EST,vitor@bu.edu,Victor,Vicente,1,1,0,1,1,1,...,0,0,0,0,1,1,0,1,0,1
4,2021/02/02 7:49:22 PM EST,srk22@bu.edu,Snigdha,Kalathur,1,0,1,1,1,0,...,0,0,0,0,0,1,0,0,1,1
5,2021/02/02 7:49:30 PM EST,johnbest@bu.edu,John,Bestavros,1,1,0,1,0,1,...,0,1,0,0,0,1,0,1,1,1
6,2021/02/02 7:49:45 PM EST,cewalsh@bu.edu,Conor,Walsh,1,0,0,1,1,1,...,0,1,0,0,0,1,0,0,0,1
7,2021/02/02 7:50:06 PM EST,sid15@bu.edu,Siddhant,Kothari,1,1,0,1,1,0,...,0,0,0,0,1,1,1,0,0,1
8,2021/02/02 7:50:08 PM EST,zwan1312@bu.edu,Zhenghui,Wang,1,0,0,1,1,0,...,0,1,0,0,0,1,0,1,0,1
9,2021/02/02 7:50:11 PM EST,shkim219@bu.edu,Seonghoo (Paul),Kim,1,0,1,1,1,0,...,1,1,0,0,0,0,1,0,1,1
10,2021/02/02 7:50:27 PM EST,gmoncau@bu.edu,Gabriel,Moncau,1,1,1,0,0,0,...,1,1,0,0,0,1,0,0,0,1
11,2021/02/02 7:50:56 PM EST,kszhao@bu.edu,Kradon,Zhao,1,0,0,1,1,1,...,0,1,0,0,0,1,1,0,1,1
12,2021/02/02 7:51:05 PM EST,jcbolo@bu.edu,John,Bolognino,1,1,0,1,1,1,...,0,1,0,0,1,1,0,0,1,1
13,2021/02/02 7:51:28 PM EST,upe@bu.edu,Amy,Feng,0,1,1,1,1,0,...,0,1,0,0,0,1,0,0,1,1
14,2021/02/02 7:51:32 PM EST,carlopez@bu.edu,Carlos,Lopez,1,1,1,1,1,1,...,0,0,1,0,0,1,0,1,1,1
15,2021/02/02 7:51:32 PM EST,darogers@bu.edu,Delaine,Rogers,1,1,1,1,1,0,...,1,1,0,0,0,1,0,0,1,1
16,2021/02/02 7:51:32 PM EST,ebudur@bu.edu,Eren,Budur,1,1,0,1,0,1,...,0,1,0,0,0,1,0,0,0,1
17,2021/02/02 7:52:19 PM EST,janamha@bu.edu,Jana Mikaela,Aguilar,1,0,1,1,1,0,...,1,0,0,0,1,1,0,0,0,1
18,2021/02/02 7:52:24 PM EST,dsullo@bu.edu,David,Sullo,1,0,1,1,1,1,...,0,1,0,0,0,1,0,1,0,1
19,2021/02/02 7:52:26 PM EST,dcmag@bu.edu,Dominic,Maglione,0,1,0,1,1,0,...,0,1,0,0,0,1,0,0,0,1
20,2021/02/02 7:52:38 PM EST,benjisg@bu.edu,Benji,Spetter-Goldstein,1,1,1,1,1,0,...,0,0,0,0,0,1,0,0,0,1
21,2021/02/02 7:52:43 PM EST,scarden@bu.edu,Savannah,Cardenas,1,1,1,1,1,0,...,1,1,0,0,0,1,0,0,0,1
22,2021/02/02 7:52:51 PM EST,agu2002@bu.edu,Anming,Gu,1,1,1,1,1,1,...,1,0,0,0,0,1,1,0,1,1
23,2021/02/02 7:53:17 PM EST,fgpacini@bu.edu,Francis,Pacini,1,1,0,1,1,0,...,0,0,0,1,0,1,0,0,1,1
24,2021/02/02 7:53:48 PM EST,pkumari@bu.edu,Priya,Kumari,0,1,0,1,1,0,...,0,1,0,0,0,1,1,0,1,1
25,2021/02/02 7:54:21 PM EST,mlopez99@bu.edu,Melissa,Lopez,1,0,0,1,1,0,...,1,1,0,0,0,1,0,1,1,1
26,2021/02/02 7:54:27 PM EST,mhenrik@bu.edu,Matt,Henriksen,1,1,1,1,1,0,...,0,1,0,0,0,1,0,0,0,1
27,2021/02/02 7:55:03 PM EST,evanlhsu@bu.edu,Evan,Hsu,1,1,1,1,1,0,...,1,0,0,1,0,1,0,0,0,1
28,2021/02/02 7:59:22 PM EST,nathanhh@bu.edu,Nathan,Ho,1,0,0,1,0,1,...,0,0,0,0,0,1,0,0,1,1

In [719]:
df['Are you interested in Product Management?']

0     1
1     0
2     0
3     1
4     0
5     0
6     1
7     1
8     1
9     0
10    1
11    0
12    0
13    0
14    0
15    0
16    1
17    1
18    0
19    1
20    0
21    1
22    1
23    0
24    1
25    0
26    0
27    0
28    0
Name: Are you interested in Product Management?, dtype: int64

In [720]:
# Looks good, lets now set the column to the new variable
# df['Are you interested in Product Management?'] = df['Are you interested in Product Management?'].apply(lambda x: 0 if x=='No' else 1)

In [721]:
# Same idea here. If we want to, we can add more weight to specific values, but for now we will just have 0 and 1
# df['Do you like vanilla ice cream?'] = df["Do you like vanilla ice cream?"].apply(lambda x: 0 if x =='No' else 1)

In [722]:
df

,Timestamp,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,...,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.,Yes
0,2021/02/02 7:49:10 PM EST,linsyw@bu.edu,Linsy,Wang,1,1,1,1,1,1,...,0,0,1,0,0,1,1,0,0,1
1,2021/02/02 7:49:12 PM EST,pkuzdzal@bu.edu,Patrick,Kuzdzal,0,1,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
2,2021/02/02 7:49:14 PM EST,emcateer@bu.edu,Erin,McAteer,1,1,1,1,1,0,...,0,1,0,0,0,1,0,0,0,1
3,2021/02/02 7:49:19 PM EST,vitor@bu.edu,Victor,Vicente,1,1,0,1,1,1,...,0,0,0,0,1,1,0,1,0,1
4,2021/02/02 7:49:22 PM EST,srk22@bu.edu,Snigdha,Kalathur,1,0,1,1,1,0,...,0,0,0,0,0,1,0,0,1,1
5,2021/02/02 7:49:30 PM EST,johnbest@bu.edu,John,Bestavros,1,1,0,1,0,1,...,0,1,0,0,0,1,0,1,1,1
6,2021/02/02 7:49:45 PM EST,cewalsh@bu.edu,Conor,Walsh,1,0,0,1,1,1,...,0,1,0,0,0,1,0,0,0,1
7,2021/02/02 7:50:06 PM EST,sid15@bu.edu,Siddhant,Kothari,1,1,0,1,1,0,...,0,0,0,0,1,1,1,0,0,1
8,2021/02/02 7:50:08 PM EST,zwan1312@bu.edu,Zhenghui,Wang,1,0,0,1,1,0,...,0,1,0,0,0,1,0,1,0,1
9,2021/02/02 7:50:11 PM EST,shkim219@bu.edu,Seonghoo (Paul),Kim,1,0,1,1,1,0,...,1,1,0,0,0,0,1,0,1,1
10,2021/02/02 7:50:27 PM EST,gmoncau@bu.edu,Gabriel,Moncau,1,1,1,0,0,0,...,1,1,0,0,0,1,0,0,0,1
11,2021/02/02 7:50:56 PM EST,kszhao@bu.edu,Kradon,Zhao,1,0,0,1,1,1,...,0,1,0,0,0,1,1,0,1,1
12,2021/02/02 7:51:05 PM EST,jcbolo@bu.edu,John,Bolognino,1,1,0,1,1,1,...,0,1,0,0,1,1,0,0,1,1
13,2021/02/02 7:51:28 PM EST,upe@bu.edu,Amy,Feng,0,1,1,1,1,0,...,0,1,0,0,0,1,0,0,1,1
14,2021/02/02 7:51:32 PM EST,carlopez@bu.edu,Carlos,Lopez,1,1,1,1,1,1,...,0,0,1,0,0,1,0,1,1,1
15,2021/02/02 7:51:32 PM EST,darogers@bu.edu,Delaine,Rogers,1,1,1,1,1,0,...,1,1,0,0,0,1,0,0,1,1
16,2021/02/02 7:51:32 PM EST,ebudur@bu.edu,Eren,Budur,1,1,0,1,0,1,...,0,1,0,0,0,1,0,0,0,1
17,2021/02/02 7:52:19 PM EST,janamha@bu.edu,Jana Mikaela,Aguilar,1,0,1,1,1,0,...,1,0,0,0,1,1,0,0,0,1
18,2021/02/02 7:52:24 PM EST,dsullo@bu.edu,David,Sullo,1,0,1,1,1,1,...,0,1,0,0,0,1,0,1,0,1
19,2021/02/02 7:52:26 PM EST,dcmag@bu.edu,Dominic,Maglione,0,1,0,1,1,0,...,0,1,0,0,0,1,0,0,0,1
20,2021/02/02 7:52:38 PM EST,benjisg@bu.edu,Benji,Spetter-Goldstein,1,1,1,1,1,0,...,0,0,0,0,0,1,0,0,0,1
21,2021/02/02 7:52:43 PM EST,scarden@bu.edu,Savannah,Cardenas,1,1,1,1,1,0,...,1,1,0,0,0,1,0,0,0,1
22,2021/02/02 7:52:51 PM EST,agu2002@bu.edu,Anming,Gu,1,1,1,1,1,1,...,1,0,0,0,0,1,1,0,1,1
23,2021/02/02 7:53:17 PM EST,fgpacini@bu.edu,Francis,Pacini,1,1,0,1,1,0,...,0,0,0,1,0,1,0,0,1,1
24,2021/02/02 7:53:48 PM EST,pkumari@bu.edu,Priya,Kumari,0,1,0,1,1,0,...,0,1,0,0,0,1,1,0,1,1
25,2021/02/02 7:54:21 PM EST,mlopez99@bu.edu,Melissa,Lopez,1,0,0,1,1,0,...,1,1,0,0,0,1,0,1,1,1
26,2021/02/02 7:54:27 PM EST,mhenrik@bu.edu,Matt,Henriksen,1,1,1,1,1,0,...,0,1,0,0,0,1,0,0,0,1
27,2021/02/02 7:55:03 PM EST,evanlhsu@bu.edu,Evan,Hsu,1,1,1,1,1,0,...,1,0,0,1,0,1,0,0,0,1
28,2021/02/02 7:59:22 PM EST,nathanhh@bu.edu,Nathan,Ho,1,0,0,1,0,1,...,0,0,0,0,0,1,0,0,1,1

### Lets just delete our drop columns, and move on to the model! Data cleaning is notorious for being the most time consuming part.

In [723]:
df.drop(drop_cols, axis=1,inplace=True)

In [724]:
df

,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,Do you like Javascript?,...,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.,Yes
0,linsyw@bu.edu,Linsy,Wang,1,1,1,1,1,1,0,...,0,0,1,0,0,1,1,0,0,1
1,pkuzdzal@bu.edu,Patrick,Kuzdzal,0,1,1,1,0,0,0,...,0,1,0,0,0,1,0,0,0,1
2,emcateer@bu.edu,Erin,McAteer,1,1,1,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
3,vitor@bu.edu,Victor,Vicente,1,1,0,1,1,1,1,...,0,0,0,0,1,1,0,1,0,1
4,srk22@bu.edu,Snigdha,Kalathur,1,0,1,1,1,0,1,...,0,0,0,0,0,1,0,0,1,1
5,johnbest@bu.edu,John,Bestavros,1,1,0,1,0,1,1,...,0,1,0,0,0,1,0,1,1,1
6,cewalsh@bu.edu,Conor,Walsh,1,0,0,1,1,1,1,...,0,1,0,0,0,1,0,0,0,1
7,sid15@bu.edu,Siddhant,Kothari,1,1,0,1,1,0,1,...,0,0,0,0,1,1,1,0,0,1
8,zwan1312@bu.edu,Zhenghui,Wang,1,0,0,1,1,0,1,...,0,1,0,0,0,1,0,1,0,1
9,shkim219@bu.edu,Seonghoo (Paul),Kim,1,0,1,1,1,0,0,...,1,1,0,0,0,0,1,0,1,1
10,gmoncau@bu.edu,Gabriel,Moncau,1,1,1,0,0,0,0,...,1,1,0,0,0,1,0,0,0,1
11,kszhao@bu.edu,Kradon,Zhao,1,0,0,1,1,1,0,...,0,1,0,0,0,1,1,0,1,1
12,jcbolo@bu.edu,John,Bolognino,1,1,0,1,1,1,0,...,0,1,0,0,1,1,0,0,1,1
13,upe@bu.edu,Amy,Feng,0,1,1,1,1,0,0,...,0,1,0,0,0,1,0,0,1,1
14,carlopez@bu.edu,Carlos,Lopez,1,1,1,1,1,1,1,...,0,0,1,0,0,1,0,1,1,1
15,darogers@bu.edu,Delaine,Rogers,1,1,1,1,1,0,0,...,1,1,0,0,0,1,0,0,1,1
16,ebudur@bu.edu,Eren,Budur,1,1,0,1,0,1,0,...,0,1,0,0,0,1,0,0,0,1
17,janamha@bu.edu,Jana Mikaela,Aguilar,1,0,1,1,1,0,0,...,1,0,0,0,1,1,0,0,0,1
18,dsullo@bu.edu,David,Sullo,1,0,1,1,1,1,0,...,0,1,0,0,0,1,0,1,0,1
19,dcmag@bu.edu,Dominic,Maglione,0,1,0,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
20,benjisg@bu.edu,Benji,Spetter-Goldstein,1,1,1,1,1,0,0,...,0,0,0,0,0,1,0,0,0,1
21,scarden@bu.edu,Savannah,Cardenas,1,1,1,1,1,0,0,...,1,1,0,0,0,1,0,0,0,1
22,agu2002@bu.edu,Anming,Gu,1,1,1,1,1,1,0,...,1,0,0,0,0,1,1,0,1,1
23,fgpacini@bu.edu,Francis,Pacini,1,1,0,1,1,0,0,...,0,0,0,1,0,1,0,0,1,1
24,pkumari@bu.edu,Priya,Kumari,0,1,0,1,1,0,0,...,0,1,0,0,0,1,1,0,1,1
25,mlopez99@bu.edu,Melissa,Lopez,1,0,0,1,1,0,1,...,1,1,0,0,0,1,0,1,1,1
26,mhenrik@bu.edu,Matt,Henriksen,1,1,1,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
27,evanlhsu@bu.edu,Evan,Hsu,1,1,1,1,1,0,1,...,1,0,0,1,0,1,0,0,0,1
28,nathanhh@bu.edu,Nathan,Ho,1,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,1,1

# Inferencing

#### Let seperate the data from its ids for now

In [725]:
X, X_data = df, df.drop(id_cols, axis=1)

In [726]:
X

,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,Do you like Javascript?,...,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.,Yes
0,linsyw@bu.edu,Linsy,Wang,1,1,1,1,1,1,0,...,0,0,1,0,0,1,1,0,0,1
1,pkuzdzal@bu.edu,Patrick,Kuzdzal,0,1,1,1,0,0,0,...,0,1,0,0,0,1,0,0,0,1
2,emcateer@bu.edu,Erin,McAteer,1,1,1,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
3,vitor@bu.edu,Victor,Vicente,1,1,0,1,1,1,1,...,0,0,0,0,1,1,0,1,0,1
4,srk22@bu.edu,Snigdha,Kalathur,1,0,1,1,1,0,1,...,0,0,0,0,0,1,0,0,1,1
5,johnbest@bu.edu,John,Bestavros,1,1,0,1,0,1,1,...,0,1,0,0,0,1,0,1,1,1
6,cewalsh@bu.edu,Conor,Walsh,1,0,0,1,1,1,1,...,0,1,0,0,0,1,0,0,0,1
7,sid15@bu.edu,Siddhant,Kothari,1,1,0,1,1,0,1,...,0,0,0,0,1,1,1,0,0,1
8,zwan1312@bu.edu,Zhenghui,Wang,1,0,0,1,1,0,1,...,0,1,0,0,0,1,0,1,0,1
9,shkim219@bu.edu,Seonghoo (Paul),Kim,1,0,1,1,1,0,0,...,1,1,0,0,0,0,1,0,1,1
10,gmoncau@bu.edu,Gabriel,Moncau,1,1,1,0,0,0,0,...,1,1,0,0,0,1,0,0,0,1
11,kszhao@bu.edu,Kradon,Zhao,1,0,0,1,1,1,0,...,0,1,0,0,0,1,1,0,1,1
12,jcbolo@bu.edu,John,Bolognino,1,1,0,1,1,1,0,...,0,1,0,0,1,1,0,0,1,1
13,upe@bu.edu,Amy,Feng,0,1,1,1,1,0,0,...,0,1,0,0,0,1,0,0,1,1
14,carlopez@bu.edu,Carlos,Lopez,1,1,1,1,1,1,1,...,0,0,1,0,0,1,0,1,1,1
15,darogers@bu.edu,Delaine,Rogers,1,1,1,1,1,0,0,...,1,1,0,0,0,1,0,0,1,1
16,ebudur@bu.edu,Eren,Budur,1,1,0,1,0,1,0,...,0,1,0,0,0,1,0,0,0,1
17,janamha@bu.edu,Jana Mikaela,Aguilar,1,0,1,1,1,0,0,...,1,0,0,0,1,1,0,0,0,1
18,dsullo@bu.edu,David,Sullo,1,0,1,1,1,1,0,...,0,1,0,0,0,1,0,1,0,1
19,dcmag@bu.edu,Dominic,Maglione,0,1,0,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
20,benjisg@bu.edu,Benji,Spetter-Goldstein,1,1,1,1,1,0,0,...,0,0,0,0,0,1,0,0,0,1
21,scarden@bu.edu,Savannah,Cardenas,1,1,1,1,1,0,0,...,1,1,0,0,0,1,0,0,0,1
22,agu2002@bu.edu,Anming,Gu,1,1,1,1,1,1,0,...,1,0,0,0,0,1,1,0,1,1
23,fgpacini@bu.edu,Francis,Pacini,1,1,0,1,1,0,0,...,0,0,0,1,0,1,0,0,1,1
24,pkumari@bu.edu,Priya,Kumari,0,1,0,1,1,0,0,...,0,1,0,0,0,1,1,0,1,1
25,mlopez99@bu.edu,Melissa,Lopez,1,0,0,1,1,0,1,...,1,1,0,0,0,1,0,1,1,1
26,mhenrik@bu.edu,Matt,Henriksen,1,1,1,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
27,evanlhsu@bu.edu,Evan,Hsu,1,1,1,1,1,0,1,...,1,0,0,1,0,1,0,0,0,1
28,nathanhh@bu.edu,Nathan,Ho,1,0,0,1,0,1,0,...,0,0,0,0,0,1,0,0,1,1

In [727]:
X_data

,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,Do you like Javascript?,Do you like playing sports?,Do your hobbies fall within the arts?,Do you do a lot of outdoor activities?,...,What about K-Pop?,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.,Yes
0,1,1,1,1,1,1,0,1,1,1,...,0,0,1,0,0,1,1,0,0,1
1,0,1,1,1,0,0,0,1,0,1,...,0,1,0,0,0,1,0,0,0,1
2,1,1,1,1,1,0,0,1,0,1,...,0,1,0,0,0,1,0,0,0,1
3,1,1,0,1,1,1,1,0,0,0,...,0,0,0,0,1,1,0,1,0,1
4,1,0,1,1,1,0,1,1,1,0,...,0,0,0,0,0,1,0,0,1,1
5,1,1,0,1,0,1,1,0,0,0,...,0,1,0,0,0,1,0,1,1,1
6,1,0,0,1,1,1,1,1,0,0,...,0,1,0,0,0,1,0,0,0,1
7,1,1,0,1,1,0,1,1,0,1,...,0,0,0,0,1,1,1,0,0,1
8,1,0,0,1,1,0,1,0,0,0,...,0,1,0,0,0,1,0,1,0,1
9,1,0,1,1,1,0,0,1,0,1,...,1,1,0,0,0,0,1,0,1,1
10,1,1,1,0,0,0,0,0,1,0,...,1,1,0,0,0,1,0,0,0,1
11,1,0,0,1,1,1,0,1,0,0,...,0,1,0,0,0,1,1,0,1,1
12,1,1,0,1,1,1,0,1,1,1,...,0,1,0,0,1,1,0,0,1,1
13,0,1,1,1,1,0,0,1,0,1,...,0,1,0,0,0,1,0,0,1,1
14,1,1,1,1,1,1,1,1,1,1,...,0,0,1,0,0,1,0,1,1,1
15,1,1,1,1,1,0,0,1,1,1,...,1,1,0,0,0,1,0,0,1,1
16,1,1,0,1,0,1,0,1,0,1,...,0,1,0,0,0,1,0,0,0,1
17,1,0,1,1,1,0,0,1,1,0,...,1,0,0,0,1,1,0,0,0,1
18,1,0,1,1,1,1,0,1,0,0,...,0,1,0,0,0,1,0,1,0,1
19,0,1,0,1,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
20,1,1,1,1,1,0,0,0,0,1,...,0,0,0,0,0,1,0,0,0,1
21,1,1,1,1,1,0,0,1,0,1,...,1,1,0,0,0,1,0,0,0,1
22,1,1,1,1,1,1,0,0,1,0,...,1,0,0,0,0,1,1,0,1,1
23,1,1,0,1,1,0,0,0,0,0,...,0,0,0,1,0,1,0,0,1,1
24,0,1,0,1,1,0,0,0,1,0,...,0,1,0,0,0,1,1,0,1,1
25,1,0,0,1,1,0,1,1,1,0,...,1,1,0,0,0,1,0,1,1,1
26,1,1,1,1,1,0,0,1,0,1,...,0,1,0,0,0,1,0,0,0,1
27,1,1,1,1,1,0,1,1,1,1,...,1,0,0,1,0,1,0,0,0,1
28,1,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,0,0,1,1

### Depending on how this goes, we can add more stuff. However for now, lets just focus on a classic kmeans model. 

### If you want more documentation use the [api](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html)

#### It'll initialize the kmeans++ algo that we talked about in our last meeting! Feel free to play around with it, and test some stuff. I would also recommend playing with some toy datasets you can find out on line if you're interested in the actual model. 

#### You can also message in the gc if you have more questions. And we can even do zoom if you guys want more theory with clustering, time-series, or NLP (I've done research in those three).

In [728]:
model = KMeans(n_clusters=7, random_state=0).fit(X_data)

In [729]:
#These are the lables, now lets stitch them back to the original data 
model.labels_

array([1, 2, 4, 1, 0, 0, 2, 4, 6, 5, 4, 5, 3, 0, 1, 0, 2, 3, 5, 2, 2, 4,
       5, 3, 4, 6, 4, 0, 5])

In [730]:
X['Labels'] = model.labels_

In [731]:
X

,Username,First Name,Last Name,Do you like vanilla ice cream?,Do you like chocolate ice cream?,Do you like strawberry ice cream?,Do you like Python?,Do you like Java?,Do you like C/C++?,Do you like Javascript?,...,Do you live on campus?,Do you live in Allston?,Do you live in Cambridge?,Do you live in Brookline?,"You want to enter the tech industry (Google, Facebook, Microsoft, Startups...).",You want to pursue a career in Finance.,You want to work in a role related to Game Design.,You want to eventually work in a role that is algorithm/math heavy.,Yes,Labels
0,linsyw@bu.edu,Linsy,Wang,1,1,1,1,1,1,0,...,0,1,0,0,1,1,0,0,1,1
1,pkuzdzal@bu.edu,Patrick,Kuzdzal,0,1,1,1,0,0,0,...,1,0,0,0,1,0,0,0,1,2
2,emcateer@bu.edu,Erin,McAteer,1,1,1,1,1,0,0,...,1,0,0,0,1,0,0,0,1,4
3,vitor@bu.edu,Victor,Vicente,1,1,0,1,1,1,1,...,0,0,0,1,1,0,1,0,1,1
4,srk22@bu.edu,Snigdha,Kalathur,1,0,1,1,1,0,1,...,0,0,0,0,1,0,0,1,1,0
5,johnbest@bu.edu,John,Bestavros,1,1,0,1,0,1,1,...,1,0,0,0,1,0,1,1,1,0
6,cewalsh@bu.edu,Conor,Walsh,1,0,0,1,1,1,1,...,1,0,0,0,1,0,0,0,1,2
7,sid15@bu.edu,Siddhant,Kothari,1,1,0,1,1,0,1,...,0,0,0,1,1,1,0,0,1,4
8,zwan1312@bu.edu,Zhenghui,Wang,1,0,0,1,1,0,1,...,1,0,0,0,1,0,1,0,1,6
9,shkim219@bu.edu,Seonghoo (Paul),Kim,1,0,1,1,1,0,0,...,1,0,0,0,0,1,0,1,1,5
10,gmoncau@bu.edu,Gabriel,Moncau,1,1,1,0,0,0,0,...,1,0,0,0,1,0,0,0,1,4
11,kszhao@bu.edu,Kradon,Zhao,1,0,0,1,1,1,0,...,1,0,0,0,1,1,0,1,1,5
12,jcbolo@bu.edu,John,Bolognino,1,1,0,1,1,1,0,...,1,0,0,1,1,0,0,1,1,3
13,upe@bu.edu,Amy,Feng,0,1,1,1,1,0,0,...,1,0,0,0,1,0,0,1,1,0
14,carlopez@bu.edu,Carlos,Lopez,1,1,1,1,1,1,1,...,0,1,0,0,1,0,1,1,1,1
15,darogers@bu.edu,Delaine,Rogers,1,1,1,1,1,0,0,...,1,0,0,0,1,0,0,1,1,0
16,ebudur@bu.edu,Eren,Budur,1,1,0,1,0,1,0,...,1,0,0,0,1,0,0,0,1,2
17,janamha@bu.edu,Jana Mikaela,Aguilar,1,0,1,1,1,0,0,...,0,0,0,1,1,0,0,0,1,3
18,dsullo@bu.edu,David,Sullo,1,0,1,1,1,1,0,...,1,0,0,0,1,0,1,0,1,5
19,dcmag@bu.edu,Dominic,Maglione,0,1,0,1,1,0,0,...,1,0,0,0,1,0,0,0,1,2
20,benjisg@bu.edu,Benji,Spetter-Goldstein,1,1,1,1,1,0,0,...,0,0,0,0,1,0,0,0,1,2
21,scarden@bu.edu,Savannah,Cardenas,1,1,1,1,1,0,0,...,1,0,0,0,1,0,0,0,1,4
22,agu2002@bu.edu,Anming,Gu,1,1,1,1,1,1,0,...,0,0,0,0,1,1,0,1,1,5
23,fgpacini@bu.edu,Francis,Pacini,1,1,0,1,1,0,0,...,0,0,1,0,1,0,0,1,1,3
24,pkumari@bu.edu,Priya,Kumari,0,1,0,1,1,0,0,...,1,0,0,0,1,1,0,1,1,4
25,mlopez99@bu.edu,Melissa,Lopez,1,0,0,1,1,0,1,...,1,0,0,0,1,0,1,1,1,6
26,mhenrik@bu.edu,Matt,Henriksen,1,1,1,1,1,0,0,...,1,0,0,0,1,0,0,0,1,4
27,evanlhsu@bu.edu,Evan,Hsu,1,1,1,1,1,0,1,...,0,0,1,0,1,0,0,0,1,0
28,nathanhh@bu.edu,Nathan,Ho,1,0,0,1,0,1,0,...,0,0,0,0,1,0,0,1,1,5

### This Notebook is more focused on the cleaning aspect. 

### In real world, we will mostly used premade frameworks, so the complicated part of the model is understanding the theory and using the correct techniques. If this goes well, we can move to hierarchical clustering. 

### However we need: 
#### 1) The data to intake (people will have to work on the google form)

#### 2) Data cleaning (exactly like we did here, the csv I supplied is directly from a google form)

#### 3) The model (A kmeans model is simple, but if we have time we'll do the more cool stuff)

In [732]:
families = {}
families['Euclid'] = []
families['Prim'] = []
families['Hopper'] = []
families['Pascal'] = []
families['Lovelace'] = []
families['Boole'] = []
families['Djikstra'] = []

for i in range(29):
    if(X['Labels'][i] == 0):
        families['Euclid'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 1):
        families['Prim'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 2):
        families['Hopper'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 3):
        families['Pascal'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 4):
        families['Lovelace'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 5):
        families['Boole'].append(X['First Name'][i] + ' ' + X['Last Name'][i])
    if(X['Labels'][i] == 6):
        families['Djikstra'].append(X['First Name'][i] + ' ' + X['Last Name'][i])

not_balanced = True    

while(not_balanced):
    
    largest_fam = ''
    largest_fam_size = 0
    
    smallest_fam = ''
    smallest_fam_size = 99
    
    for family in families:
        if(len(families[family]) > largest_fam_size):
            largest_fam_size = len(families[family])
            largest_fam = family
        if(len(families[family]) < smallest_fam_size):
            smallest_fam_size = len(families[family])
            smallest_fam = family
        
    if(largest_fam_size - smallest_fam_size > 1):
        member_to_move = families[largest_fam].pop([largest_fam_size - 1])
        families[smallest_fam].append(member_to_move)
    else:
        not_balanced = False


for family in families:
    print(family)
    print(families[family])
    print()

TypeError: 'list' object cannot be interpreted as an integer